# Generated by Django 3.0.6 on 2020-12-31 23:01

from django.db import migrations, models

def create_data(apps,schema_editor):
    Account=apps.get_model('userApp','Account')
    Account(firstName="FirstName",lastName="LastName",email="user@gmail.com",phoneNumber="0000000",password="userpassword",confirmPassword="userpassword").save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=1000, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=1000, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=1000, verbose_name='Email')),
                ('phoneNumber', models.CharField(max_length=1000, verbose_name='phoneNumber')),
                ('password', models.CharField(max_length=2000, verbose_name='password')),
                ('confirmPassword', models.CharField(max_length=2000, verbose_name='repassword')),
            ],
        ),
    ]
