# Generated by Django 3.0.6 on 2021-01-18 12:35

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20210118_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='tokenNumber',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
