# Generated by Django 3.0.6 on 2021-01-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_auto_20210118_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessToken', models.CharField(max_length=20000, verbose_name='Access Token')),
                ('googleID', models.CharField(max_length=20000, verbose_name='Google Id ')),
                ('name', models.CharField(max_length=20000, verbose_name='Name')),
                ('email', models.CharField(max_length=20000, verbose_name='Email')),
                ('firstName', models.CharField(max_length=20000, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=20000, verbose_name='Last Name')),
                ('imageUrl', models.CharField(max_length=20000, verbose_name='Image')),
            ],
        ),
        migrations.DeleteModel(
            name='UserToken',
        ),
    ]
