# Generated by Django 3.0.6 on 2021-01-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_auto_20210119_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertokens',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='usertokens',
            name='lastName',
        ),
    ]
