# Generated by Django 3.0.6 on 2021-01-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_auto_20210119_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokens',
            name='email',
            field=models.EmailField(max_length=20000, verbose_name='Email'),
        ),
    ]
