# Generated by Django 3.0.6 on 2021-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0008_auto_20210119_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dp',
            field=models.ImageField(blank=True, default='media/images/pp.jpg', null=True, upload_to='media/images'),
        ),
    ]
