# Generated by Django 3.0.6 on 2021-02-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0009_account_dp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dp',
            field=models.ImageField(blank=True, default='/images/pp.jpg', null=True, upload_to='images'),
        ),
    ]
