# Generated by Django 3.0.6 on 2021-02-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0010_auto_20210205_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dp',
            field=models.ImageField(blank=True, default='media/images/pp.jpg', null=True, upload_to='media/images'),
        ),
    ]
