# Generated by Django 3.0.6 on 2021-04-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0011_auto_20210206_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=200, verbose_name='Book')),
                ('typeOfBook', models.CharField(max_length=2000, verbose_name='typeOfBook')),
                ('nameOfWriter', models.CharField(max_length=5000, verbose_name='nameOfWriter')),
                ('labelPriceBook', models.CharField(max_length=1000, verbose_name='labelPriceBook')),
                ('bookImage', models.ImageField(blank=True, null=True, upload_to='media/images')),
                ('nameOfBook', models.CharField(max_length=10000, verbose_name='nameOfBook')),
                ('dateOfPublication', models.DateField(null=True, verbose_name='dateOfPublication')),
                ('conditionBook', models.CharField(max_length=20000, verbose_name='conditionBook')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userApp.Account')),
            ],
        ),
    ]
