# Generated by Django 3.0.6 on 2021-04-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0012_bookinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinformation',
            name='status',
            field=models.CharField(default='addedOnList', max_length=10000),
        ),
    ]
