# Generated by Django 3.0.6 on 2021-04-02 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0013_bookinformation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinformation',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='bookinformation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookInformation', to='userApp.Account'),
        ),
    ]
