# Generated by Django 3.0.6 on 2021-04-16 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0014_auto_20210402_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='addedOnList', max_length=10000)),
                ('notesType', models.CharField(max_length=10000, verbose_name='notesType')),
                ('noteTitle', models.CharField(max_length=10000, verbose_name='noteTitle')),
                ('notePrice', models.CharField(max_length=10000, verbose_name='notePrice')),
                ('noteFaculty', models.CharField(max_length=50000, verbose_name='noteFaculty')),
                ('noteExplanation', models.CharField(max_length=10000, verbose_name='noteExplanation')),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notesInformation', to='userApp.Account')),
            ],
        ),
    ]
