# Generated by Django 3.0.6 on 2021-04-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0015_notesinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinformation',
            name='bookImage',
            field=models.ImageField(blank=True, null=True, upload_to='media/images', verbose_name='bookImage'),
        ),
    ]
