# Generated by Django 3.1.1 on 2021-07-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0016_auto_20210420_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='dp',
            field=models.ImageField(blank=True, default='media/images/pp.jpg', null=True, upload_to='media/images', verbose_name='dp'),
        ),
        migrations.AlterField(
            model_name='bookinformation',
            name='labelPriceBook',
            field=models.IntegerField(verbose_name='labelPriceBookk'),
        ),
    ]
