# Generated by Django 3.1.1 on 2021-07-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0017_auto_20210721_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesinformation',
            name='notePrice',
            field=models.IntegerField(max_length=10000, verbose_name='notePrice'),
        ),
    ]
