# Generated by Django 3.1.1 on 2021-07-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0018_auto_20210721_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesinformation',
            name='notePrice',
            field=models.IntegerField(verbose_name='notePrice'),
        ),
    ]
