# Generated by Django 3.1.1 on 2021-07-27 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0019_auto_20210721_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000, verbose_name='userName')),
                ('nameOfWriterRecommendation', models.CharField(max_length=5000, verbose_name='nameOfWriterRecommendation')),
                ('review', models.TextField(max_length=10000, verbose_name='review')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='userApp.account')),
            ],
        ),
    ]
