# Generated by Django 3.1.1 on 2021-07-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0020_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='bookName',
            field=models.CharField(max_length=2000, null=True, verbose_name='bookName'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='name',
            field=models.CharField(max_length=2000, null=True, verbose_name='userName'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='nameOfWriterRecommendation',
            field=models.CharField(max_length=5000, null=True, verbose_name='nameOfWriterRecommendation'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='review',
            field=models.TextField(max_length=10000, null=True, verbose_name='review'),
        ),
    ]
